### ISSUE TITLE
添加二维码补全功能

### ISSUE THREAD

**Issue by moyuwa** [zR00t1/ImageStrike#1]
CTF常见的缺少三个定位角，实现二维码补全功能，比如4个角选择性显示，可以手动调整4个图片大小，然后补全图片

**Comment by zR00t1** [comment]
这种我一般是新建一个PPT，拖上定位点的图片和二维码图片，手动调整大小和位置进行处理。如果写成自动化工具的话，要考虑每个题目给出的图片可能不同，可能没有通用的处理方法。如果你有好的处理方法和骚思路可以联系我~~
